// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

Future<SystemProxy> getProxy() => RustLib.instance.api.crateApiProxyGetProxy();

class SystemProxy {
  final bool enable;
  final String host;
  final int port;
  final String bypass;

  const SystemProxy({
    required this.enable,
    required this.host,
    required this.port,
    required this.bypass,
  });

  static Future<SystemProxy> default_() =>
      RustLib.instance.api.crateApiProxySystemProxyDefault();

  @override
  int get hashCode =>
      enable.hashCode ^ host.hashCode ^ port.hashCode ^ bypass.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemProxy &&
          runtimeType == other.runtimeType &&
          enable == other.enable &&
          host == other.host &&
          port == other.port &&
          bypass == other.bypass;
}
